### ISSUE TITLE
Segmentation format when create tf_record from csv dataset

### ISSUE THREAD

**Issue by felihong** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#20]
Hi @TannerGilbert , 

thanks for providing such a great tutorial! :) 

While training using `mask_rcnn_inception_resnet_v2_atrous_coco`  I ran into the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [max value is lower than 1.01: ] [0]
	 [[{{node Loss/BoxClassifierLoss/ToNormalizedCoordinates/Assert/AssertGuard/Assert}}]]
	 [[Cast_2/_6005]]
  (1) Invalid argument: assertion failed: [max value is lower than 1.01: ] [0]
	 [[{{node Loss/BoxClassifierLoss/ToNormalizedCoordinates/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored.
```
I noticed that this might has something to do with the `tf_record` that I created (plz point out here if you have other ideas). As I generated the tf_record not based on coco_dataset, I wonder if you might provide more insights about the segmentation format (with the `annotations_list`) you are using in the `create_tf_example` function:
https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model/blob/e65aacc9e9308e5435185a77086a771d4a7dc93b/create_coco_tf_record.py#L147

The current dataset (in .csv) I am using to generate the tf_record has the following schema:
```
filename, xmin, ymin, xmax, ymax, segmentation, class
```
where `segmentation` is a list of list containing polygon pixel coordinates, looking like the following:
```
[[1315, 1295, 1318, 1282, 1349, 1241, 1366, 1227, 1367, 1239, 1344, 1263, 1340, 1268, 1327, 1284]]
```

Is the the correct format to generate tf_records with masks? Do I need to normalize the polygon coordinates here? 
Any suggestions would be very appreciated! Thanks 😊

**Comment by felihong** [comment]
FYI I changed the default setting `check_range` of function `to_normalized_coordinates` to False (in `models/research/object_detection/core/box_list_ops.py`). And this temporarily suppressed the assertion. Assumption would be some of the annotation areas are being too small.
