### ISSUE TITLE
Tutorial did'nt work

### ISSUE THREAD

**Issue by greg007-web** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#24]
Hi, thanks for your tutorial.
And sorry to disturb you.
But I would like a little help, if is possible. I'm working based on your turorial and I'm using Colab pro. But I had some problems. 
Here my colab with the problems: 
https://colab.research.google.com/drive/14wVrKTSZLBu4fhov3Oy1CzhixB2u5s4j#scrollTo=FWKz8O9arbQw 

Basicly I can't run my program. Please, can you help me?

If you need some further information let me know!
And again thanks for your support.

**Comment by TannerGilbert** [comment]
The following error:

```
Traceback (most recent call last):
  File "/content/models/research/object_detection/builders/model_builder_tf2_test.py", line 22, in <module>
    import tensorflow.compat.v1 as tf
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 473, in <module>
    keras._load()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/usr/local/lib/python3.7/dist-packages/keras/metrics.py", line 27, in <module>
    from keras import activations
  File "/usr/local/lib/python3.7/dist-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 41, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/usr/local/lib/python3.7/dist-packages/keras/mixed_precision/loss_scale_optimizer.py", line 1180, in <module>
    mixed_precision._register_wrapper_optimizer_cls(optimizer_v2.OptimizerV2,
AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'
```

is occuring because you're using Tensorflow 2.5. Just upgrade to Tensorflow >=2.6 and it should work.
