### ISSUE TITLE
RuntimeError: Groundtruth tensor boxes has not been provided

### ISSUE THREAD

**Issue by Nagaraj4896** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#8]
Got This **(RuntimeError: Groundtruth tensor boxes has not been provided)** Error while training started on GPU in my machine and your colab notebook also

```
I0318 16:34:11.815828 140694853109568 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "TensorFlow/models/research/object_detection/model_main_tf2.py", line 118, in <module>
    tf.compat.v1.app.run()
  File "/home/gaming/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/gaming/anaconda3/envs/tensorflow/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/gaming/anaconda3/envs/tensorflow/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "TensorFlow/models/research/object_detection/model_main_tf2.py", line 109, in main
    model_lib_v2.train_loop(
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/model_lib_v2.py", line 525, in train_loop
    dummy_prediction_dict = detection_model.predict(dummy_image, dummy_shapes)
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 824, in predict
    self._predict_second_stage(
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 997, in _predict_second_stage
    proposal_boxes_normalized, num_proposals = self._proposal_postprocess(
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 727, in _proposal_postprocess
    self._postprocess_rpn(
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1754, in _postprocess_rpn
    ) = self._format_groundtruth_data(image_shapes)
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1891, in _format_groundtruth_data
    self.groundtruth_lists(fields.BoxListFields.boxes))
  File "/home/gaming/DIC_training/TensorFlow/models/research/object_detection/core/model.py", line 117, in groundtruth_lists
    raise RuntimeError('Groundtruth tensor {} has not been provided'.format(
RuntimeError: Groundtruth tensor boxes has not been provided
```

**Comment by damianozappia** [comment]
I'm facing the same problem running the code on colab. Any solution?

**Comment by TannerGilbert** [comment]
Take a look at the following related issues:
* https://github.com/tensorflow/models/issues/9808
* https://github.com/tensorflow/models/issues/9738
